
dsh: 2
ns: flash.flange

vars:
  app: flange

test:
  - tox

install:
  - pip install -e .

build:
  - rm -rf build
  - rm -rf dist
  - python setup.py sdist bdist_wheel
  - ls -l dist

release:
  - tox
  - rm -rf build
  - rm -rf dist
  - python setup.py sdist bdist_wheel
  - twine upload -r pypi dist/flange*
