
dsh: 2
ns: flange

init: 
  - pip install -U pip setuptools wheel twine keyring

test:
  - nosetests

install:
  - pip install -e .

package:
  - rm -rf build
  - python setup.py sdist bdist_wheel

publish:
  - twine upload -r pypi dist/flange*
